#!/usr/bin/env fish

# Checking if username was entered
if [ (count $argv) -lt 1 ]
    echo "Usage: $argv[0] <username> [<usedefaultpasswd>]"
    exit 1
else if [ (count $argv) -gt 2 ]
    echo "Usage: $argv[0] <username> [<usedefaultpasswd>]"
    exit 1
end

set username $argv[1]
set defaultpasswd $argv[2]

set PORT 2200

while true
    nc -zv localhost $PORT > /dev/null 

    if test $status -eq 0
        set PORT (math $PORT + 1)
    else
        break
    end
end 

set userdirectory (realpath ~/Desktop/ProgrammingComp/Submissions/$username)

if not test -d $userdirectory
    # If it doesn't exist, create it
    mkdir -p $userdirectory
end

# Printing that the container was successful 
echo "Running $username's container"
echo "Using port $PORT"

# Running the Docker image
docker run -t -v ~/Desktop/ProgrammingComp/Problems:/problems:ro -v $userdirectory:/submissions -e USER=$username -e DEFAULTPASSWD=$defaultpasswd -p $PORT:22 users 
