#!/bin/bash

# Checking if username was entered
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Username argument
username="$1"

# Port variable
PORT=2200

# Check if the port is open
while true; do
nc -zv localhost $PORT > /dev/null 
    # If not go to the next one
    if [ $? -eq 0 ]; then
    PORT=$(expr $PORT + 1)
    else
        break
    fi

done 

# Printing that the container was successful 
echo "Running $username's container"

# Printing what port you're using
echo "Using port $PORT"

# Running the docker image
docker run -t -v ~/tmp:/tmp -e USER="$username" -p $PORT:22 users 
 

   
