#!/usr/bin/env fish

# Checking if directory was entered
if test (count $argv) -ne 1
    echo "Must include path to the Dockerfile directory"
    exit 1
end

set directory $argv[1]

# Building the Dockerfile
docker build -t users $directory
